# Individual Video Processing Tasks (kickoff_for_each)
video_analysis_task:
  description: >
    Analyze a SINGLE video file using Gemini's video understanding API to create a short summary of the project demo.
    
    You have been provided with:
    - video_path: The path to a single video file to process
    - video_filename: The name of the video file
    - attendee_list: List of attendees (if available)
    
    CRITICAL: The video file is located at: {video_path}
    This is the EXACT path you must pass to the Gemini Video Tool.
    
    For this video:
    1. Use the Gemini Video Tool to analyze the video at {video_path}
       - Pass the EXACT path: {video_path}
       - Enable transcribe=True for audio transcription
    2. Extract from the tool output:
       - Project Name (look for "Project Name:" in the response)
       - Description (look for what the project does)
       - Any impressive features or innovations
    3. Format the extracted information into the required output format

    If the API returns an error, try again!
    
    IMPORTANT: Always use the actual project information from the tool output.
    If the tool provides a project name like "PaperTrail" or "CrewAI", use that exact name.
    DO NOT use "Unknown Project" if the tool successfully extracted a project name.
    
    Create a summary following this EXACT format:
    
    [Actual Project Name from tool output]
    
    [One-line description of what it does]
    
    [Catchy tagline or category]
    [@unknown]

  expected_output: >
    A single project summary in the EXACT format specified:
    
    [Project Name from Gemini tool output]
    
    [One-line description of what the project does, ending with a period.]
    
    [Catchy tagline or category phrase]
    [@unknown]
    
    CRITICAL: Use the ACTUAL project information from the Gemini tool output.
    Do NOT use generic placeholders like "Unknown Project" if the tool provided real information.
  agent: video_summarizer

person_research_task:
  description: >
    Research the project participants from the analyzed video:
    
    Based on the project identified in the video_analysis_task:
    1. Use the attendee list {attendee_list} as reference if available
    2. Search for their Twitter/X profiles
    3. Find their LinkedIn or other professional profiles if possible
    4. Verify their association with the project
    5. Collect relevant handles and profile links
    
    IMPORTANT: If Twitter handles cannot be found, that's perfectly acceptable!
    The search tool may not always find profiles, especially for:
    - People with common names
    - People without Twitter accounts
    - People with private profiles
    
    In these cases, simply note that handles were not found and move on.
    
    Ensure all information is publicly available and accurate.
  expected_output: >
    A participant report for this project containing:
    - Project name
    - Names of team members (if identified)
    - Twitter/X handles (if found - it's OK if none are found!)
    - Other relevant social media links (if found)
    - Brief bio or role in the project (if available)
    
    If no profiles are found, simply state:
    "No social media profiles found for this project's team members"
  agent: person_finder
  context:
    - video_analysis_task

create_tweet_summary_task:
  description: >
    Format the video analysis results into a tweet-ready summary.
    
    DO NOT analyze any videos - the video_analysis_task has already done this.
    Simply take the output from video_analysis_task and ensure it follows
    the correct tweet format.
    
    The video_analysis_task output should already contain:
    - Project name
    - One-line description
    - Tagline
    - Twitter handle (use @unknown)
    
    Your job is ONLY to verify the format and pass it through.
    DO NOT use any tools. DO NOT analyze videos.
  expected_output: >
    A single tweet-ready project summary in this format:
    
    [Project Name]
    
    [One-line description]
    
    [Tagline]
    [@unknown]
  agent: video_summarizer
  context:
    - video_analysis_task

# Aggregation Tasks (single kickoff)
aggregate_summaries_task:
  description: >
    Collect and organize all individual video summaries that were processed.
    
    CRITICAL: You are receiving ACTUAL summaries from real video processing.
    DO NOT create fake projects or example data.
    
    The summaries to process are:
    {all_summaries}
    
    Total number of videos processed: {video_count}
    
    Your task is to:
    1. Parse through the summaries provided above
    2. Count exactly how many projects were included (should be {video_count})
    3. Extract each project's details:
       - Project Name (first line of each summary)
       - One-line description (second line)
       - Tagline (third line)
       - Twitter handles (fourth line)
    4. Present them in a clear, numbered list
    5. DO NOT add any fake or example projects - use ONLY what's provided above
    
    Format each summary clearly:
    Project #1:
    - Name: [actual name from summary]
    - Description: [actual description]
    - Tagline: [actual tagline]
    - Twitter: [actual handle]
  expected_output: >
    A consolidated list of the ACTUAL project summaries from video processing.
    Must include EXACTLY {video_count} project(s).
    Each project should be clearly numbered and formatted.
    NO fake or example projects - only use the real data provided above.
  agent: thread_composer

video_ranking_task:
  description: >
    Analyze and rank the processed video summaries based on engagement potential.
    
    CRITICAL: Use ONLY the actual projects from the aggregate_summaries_task output.
    DO NOT create fake projects. If only one project was processed, rank only that one project.
    
    The aggregate_summaries_task has provided you with the actual project details.
    
    Ranking criteria:
    1. Innovation and uniqueness of the project
    2. Quality of the presentation (based on the summaries)
    3. Technical impressiveness
    4. Potential for social media engagement
    5. Story-telling and narrative quality
    
    Rank the actual projects (not fictional ones) from most to least engaging for social media.
  expected_output: >
    A ranking report that includes:
    - ONLY the actual projects from aggregate_summaries_task (no fake projects)
    - If only 1 project exists, provide analysis for just that 1 project
    - Viral potential assessment for each real project
    - Key strengths that make projects stand out
    - Clear ordering recommendation for the tweet thread
  agent: video_ranker
  context:
    - aggregate_summaries_task

team_research_task:
  description: >
    Based on the analyzed video, go to https://weavehacks-1.devpost.com/project-gallery and find the names of the people who were part of the team in the video:
    
    Based on the project identified in the video_analysis_task:
    1. Report all social media profile links or handles of the people who were part of the team.
    2. Find their X or Twitter handles if possible
  expected_output: >
    A list of names and social media handles of the people who were part of the team.
  agent: person_finder
  context:
    - video_analysis_task

final_tweet_composition_task:
  description: >
    Compose the final tweet thread using all gathered information:
    
    CRITICAL REQUIREMENTS:
    1. You MUST use ONLY the actual project summaries from the previous aggregate_summaries_task
    2. DO NOT create fake or example projects
    3. DO NOT hallucinate project names like "SaveThePlanet" or "CodeConnect"  
    4. Use EXACTLY the projects from the aggregated summaries (provided by aggregate_summaries_task)
    5. Follow the ranking order from video_ranking_task
    
    The previous tasks have provided:
    - Aggregated summaries with all project details (from aggregate_summaries_task)
    - Ranking order for the projects (from video_ranking_task)
    
    If only ONE project was processed, create a thread with:
    - The intro section (3 parts)
    - ONE project tweet for that single project
    
    Thread format:
       FIRST: Start with a compelling 3-part introduction (NO NUMBERING):
       ```
       Join us as we unveil the groundbreaking projects from our latest hackathon! 🚀
       
       Innovation meets practical solutions in these exciting demonstrations.
       
       Discover the tools and ideas shaping tomorrow (🧵):
       
       
       
       
       ```
       
       THEN: Add numbered tweets for EACH project from the aggregated summaries:
       ```
       1/ [Project Name from aggregated summaries]
       
       [Description from aggregated summaries]
       
       [Tagline from aggregated summaries]
       [Twitter handles from aggregated summaries]
       
       
       
       
       2/ [Next project if exists]
       ...
       ```
       
    - Use the exact project details from aggregate_summaries_task
    - Order projects based on the video_ranking_task recommendations
    - Each tweet MUST be separated by EXACTLY 4 blank lines
    - Include ONLY the projects that were actually processed
    - If Twitter handles show as @unknown, you should omit them
    
    2. Use the Typefully API tool (typefully_api) to create a draft:
       - Pass the entire thread content to the tool
       - Set threadify=true to handle thread splitting
       - Set share=true to get a shareable link
    
    3. Save the thread content to the output file
  expected_output: >
    A complete tweet thread that includes:
    - ONLY the actual projects from the context (no fake projects)
    - The exact number of projects that were processed
    - Projects ordered based on the ranking recommendations
    - Proper formatting with 4 newlines between tweets
    - Confirmation that the draft was created in Typefully
    - The shareable link from Typefully
  agent: thread_composer
  context:
    - aggregate_summaries_task
    - video_ranking_task 